### ISSUE TITLE
[Bug]: -bash: brew: command not found and Core Dumped

### ISSUE THREAD

**Issue by Takla101** [paljsingh/impartus-downloader#101]
- OS: [Google Cloud Console]

![74545](https://user-images.githubusercontent.com/91128541/134200659-63279063-3af2-4b6e-a107-7c0d44d4f10d.PNG)

**Additional context**
i didnt have good pc so did it on google cloud console
it shows 'bash' again and again 
And now it is showing "core dumped" after I run App.py
requirements file was successfully installed but after that none of the command work

**Comment by paljsingh** [comment]
It would not work on google console for 2 reasons - 

1) google-console is cli only, it won't be able to display GUI apps (unless you know how to run X server and port forward for display)
Easier way, get a Linux / Windows machine, and follow the instructions for installation as in the link below.

2) brew cli is for mac only.

For windows/Linux, you can follow the instructions here - 

https://github.com/paljsingh/impartus-downloader#installation--run
