### ISSUE TITLE
Unable to run successfully on windows

### ISSUE THREAD

**Issue by SomeoneHere123** [paljsingh/impartus-downloader#2]
OS.path and OS.xxx functions do not seem to retrieve the required path type. There is no HOME present explicitly in my windows profile, however when I created one, the script throwed an error:
expected escape sequence of 8 hexdecimal numbers, but found 's'
  in "<unicode string>", line 2, column 18:
    target_dir: "C:\Users\XYZ/wilp"
                     ^

After changing this to expected pattern of "C:/Users/XYZ", the script ran, and opened firefox and everything, but failed after downloading in firefox:

c:\sw\impartus-downloader>python impartus.py
Files will be saved at: C:/Users/XYZ/wilp

---

Traceback (most recent call last):
  File "c:\sw\impartus-downloader\impartus.py", line 129, in <module>
    impartus.process_videos()
  File "c:\sw\impartus-downloader\impartus.py", line 68, in process_videos
    media_files = self.browser.get_media_files(ttid)
  File "c:\sw\impartus-downloader\browser\firefox.py", line 159, in get_media_files
    conn = sqlite3.connect(self.indexed_db())
  File "c:\sw\impartus-downloader\browser\firefox.py", line 171, in indexed_db
    db = os.path.join(os.path.dirname(media_dir), os.path.basename(media_dir).split('.')[0] + ".sqlite")
  File "C:\sw\python3\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "C:\sw\python3\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by paljsingh** [comment]
Thanks for reporting the issue. I am trying to get hold of a windows box for testing this out. Should be able to fix this by tomorrow.

**Comment by paljsingh** [comment]
Fixed in branch 'windows'  (https://github.com/paljsingh/impartus-downloader/tree/windows) 
PR -   https://github.com/paljsingh/impartus-downloader/pull/3 

I tested the changes on virtualbox windows 10 image.
Let me know if if it works for you, I can go ahead and merge the changes with master.
