### ISSUE TITLE
[Bug]: Error while running python App.py

### ISSUE THREAD

**Issue by Anusha1910** [paljsingh/impartus-downloader#94]
lenovo@DESKTOP-JP72497 MINGW64 /e/impartus-downloader (master)
$ python App.py
Traceback (most recent call last):
  File "E:\impartus-downloader\App.py", line 46, in <module>
    App().run()
  File "E:\impartus-downloader\App.py", line 26, in __init__
    Callbacks().setup(
TypeError: setup() missing 1 required positional argument: 'app'

**Comment by paljsingh** [comment]
I missed a checkin..
can you please do a git pull  and see if it is working ?

**Comment by paljsingh** [comment]
fixed with commit id: 4e17fe836645e02654d12af4d94f749ba85aea8e

**Comment by Anusha1910** [comment]
Thanks. Its working now.
