### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DabanggHL** [paljsingh/impartus-downloader#98]
I have installed all three things git python & ffmpeg but whenever I click on App , python opens for a second and it closes automatically 

 - OS: [Windows 10]
 - Python Version 3.6
https://user-images.githubusercontent.com/87260709/125348710-346ce880-e37a-11eb-96f6-87ffefa9acc3.MOV

**Comment by paljsingh** [comment]
Follow the installation instructions:

Run these on command prompt.


git.exe clone https://github.com/paljsingh/impartus-downloader.git
cd impartus-downloader

pip3.exe install -r requirements.txt

Then Download win64-gpl zip from the following link, extract and copy ffmpeg.exe to
impartus-downloader folder. 
[https://github.com/BtbN/FFmpeg-Builds/releases]


Ensure ffmpeg version is >= 4.3.0 , by running 

ffmpeg.exe -version 

and finally Run application as

python.exe App.py

**Comment by DabanggHL** [comment]
I am getting this error while running code on command prompt![image](https://user-images.githubusercontent.com/87260709/125401903-61001f00-e3d1-11eb-9e55-1603ae3e949b.jpeg)

**Comment by paljsingh** [comment]
https://www.youtube.com/watch?v=J_Clau1bYco
You need to have git installed.

**Comment by DabanggHL** [comment]
I have installed git and now I am stuck at this step ...help me out![image](https://user-images.githubusercontent.com/87260709/125423020-8e90cef7-6608-4766-a15e-2fa0581fb6c5.jpeg)

**Comment by paljsingh** [comment]
Check if you have python and pip installed?
https://www.youtube.com/watch?v=dYfKJMPNMDw

**Comment by DabanggHL** [comment]
Yes boss finally it's working !!!👌🏻👌🏻👌🏻
Thanks so much bro 👍
