### ISSUE TITLE
[Bug]: Login Error

### ISSUE THREAD

**Issue by MayuraVerma** [paljsingh/impartus-downloader#99]
ERROR:Impartus:Error authenticating to https://a.impartus.com/api/auth/signin with username *************@wilp.bits-pilani.ac.in.
ERROR:Impartus:Http response code: 401, response body: {"success":false,"mailSent":true}:

**Comment by paljsingh** [comment]
Can you confirm if
- you are able to login to impartus site via web browser (using same credentials)
- if password contains any special characters , I am currently not json_encoding the credentials while sending it to auth api, so any special chars may be causing the issue.
- If you have reset your password recently, may try using the old password in case it is not synced with impartus server.
-

**Comment by MayuraVerma** [comment]
It was my mistake. I had the password wrong! Sorry.
